chip_size: 11
features_labels_path: E:\Material\Object\RadarSentinelClass\Data\features_labels.h5
labels_path: E:\Material\Object\RadarSentinelClass\Data\Labels\labels.tif
radar_vh_dir: E:\Material\Object\RadarSentinelClass\Data\VHs
radar_vv_dir: E:\Material\Object\RadarSentinelClass\Data\VVs
root_dir: D:\PyProJect\RadarClass
save_dir: E:\Material\Object\RadarSentinelClass\Data
stride: 1
test_samples: 62347
train_samples: 249385
yours: me
