# root directory of the project

root_dir: D:\PyProJect\RadarClass

radar_vv_dir: E:\Material\Object\RadarSentinelClass\Data\VVs
radar_vh_dir: E:\Material\Object\RadarSentinelClass\Data\VHs

labels_path: E:\Material\Object\RadarSentinelClass\Data\Labels\labels.tif
features_labels_path: E:\Material\Object\RadarSentinelClass\Data\features_labels.h5

save_dir: E:\Material\Object\RadarSentinelClass\Data

chip_size: 11
stride: 1