# root directory of the project

root_dir: D:\PyProJect\RadarClass

radar_vv_dir: E:\Material\Object\RadarSentinelClass\Data\VVs
radar_vh_dir: E:\Material\Object\RadarSentinelClass\Data\VHs

labels_path: E:\Material\Object\RadarSentinelClass\Data\Labels\labels.tif

save_dir: D:\PyProJect\RadarClass\data

chip_size: 11
stride: 1